spring:
  application:
    name: employee-address
  data:
    datasource:
      url: jdbc:postgresql://postgressql:5432/${POSTGRESQL_DATABASE_NAME}
      username: ${POSTGRESQL_DATABASE_USER}
      password: ${POSTGRESQL_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

feign:
  hystrix:
    enabled: true
    
microservices:
  employee:
    url: http://${EMPLOYEE_SERVICE}:8080

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"